[package]
name = "test_utils"
version = "0.19.24"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.20.3"
uuid = { version = "1.18.1", features = ["v4"] }
copy_dir = "0.1.3"
chrono = "0.4.42"
